### PR TITLE
Use RazorEngine's internal caching; consider the current request path…

### PR DESCRIPTION
**Pull request by matthid**
… for resolving; resolve views in the 'Views' folder; Localize the view depending on the Accept-Language header; Add some helpers to read header values.

Note: This is breaking because now views are resolved in the "Views" folder (like Nancy does it)

This PR can be seen as a suggestion (in fact it is just a copy of the code I'm using in one of my apps I just started to write with suave) of how I imagined the RazorEngine API to be used... As I just started to use suave its unlikely that I followed all guidelines and the philosophy behind suave. 

Especially the "Headers" module is a bit wanky because ideally we would cache the parsed data in the request itself, but I couldn't figure out a good way to do it. Suggestions are welcome.

### CODE REVIEW

**Comment by ademar** [comment]
Can we look for the razor file in the homeDirectory if the file is not found under View ?

**Comment by matthid** [comment]
Yes I could add that, but ideally I would like to make the "Views" directory configurable. Any idea how to do that (to properly fit into suave)? Ideally we let users configure multiple folders such that they can put layouts and regular views in different folders if they like to. 

If there is no good way to do it (in order to keep suave simple for example) I think a fallback is fine as well to be backwards compatible. Do you prefer the simple fallback for now?

**Comment by ademar** [comment]
Yeah I think a simple fall-back should be fine so it stays compatible.

I don't know how useful would be to make the "Views" folder configurable, we already have the concept of a `homeDirectory`.

It would make sense to just have 
```fsharp
viewPath = Path.Combine(homeDirectory, "Views")
```

**Comment by matthid** [comment]
Ok the fallback is now implemented and the variable has been removed. Please review the changes I've done to the `resolvePath` in order to support `.`.

**Comment by ademar** [comment]
I think we can merge it. What do you say @haf ?

**Comment by haf** [comment]
Yes, looks good! Thanks @mathid

**Pull request merged**
