### PR TITLE
dotliquid registerFiltersByName, options, arrays

### PR DESCRIPTION
**Pull request by jackmott**
This fixes dotLiquid registerFiltersByName, such that it will search the users assembly instead of only the suave.DotLiquid.dll assembly, for modules of the name `name`. Also switched to a probably marginally more efficient search of the assemblies which is no less readable using Array.find

This also fixes array support, types within arrays are now properly registered. This was not working properly in my previous PR/

This also adds support for options, by registering the Value field you can use them in templates like so:

```html
{% for decoder in model.decoders %}  
  {% if decoder.Value %}               
    <option value="{{decoder.Value.x}}">{{decoder.Value.x}}</option>
  {% endif %}
{% endfor %}
```

### CODE REVIEW

**Comment by jackmott** [comment]
I can't tell why the AppVeyor test failed, any tips?

**Comment by adamchester** [comment]
It's the wrong obtain URL now, or perhaps they deleted the old CLI tools from their temporary azure storage.

**Comment by adamchester** [comment]
I would imagine it's best to do this in a separate PR.

**Comment by jackmott** [comment]
Any concerns with this PR? Checks pass now.

**Comment by ademar** [comment]
Thanks!

**Pull request merged**
