### PR TITLE
Add .editorconfig file.  See http://editorconfig.org/

### PR DESCRIPTION
**Pull request by jhugard**
Add editorconfig file to help compliance with style guide.

### CODE REVIEW

**Comment by haf** [comment]
+1. Any reason for all the changes to the sln file?

**Comment by jhugard** [comment]
No, largely unintentional.  Only significant change is to add neuroscientist to the solution.  Sorry, thought about cleaning that up, but was in a hurry this morning.

It's probably just an artifact of using different Visual Studio patch levels or versions. Note that the differences are mostly GUIDs changing case.

**Comment by jhugard** [comment]
neuroscientist == iPhone spelling correction of .editorconfig:p

**Comment by jhugard** [comment]
Updated to just include the .editorconfig file (no solution file changes).

**Comment by ademar** [comment]
Thanks!

**Pull request merged**
