### PR TITLE
Indicate FsLibTool run success - fixes #466

### LINKED ISSUE #466: Indicate build success: "FsLibTool: Failed to resolve" looks like build failure
This happens for `:docs:reference` rake task:

```
packages\docs\FsLibTool\tools\FsLibTool.exe src docs/_site
Generating reference for Suave.
Failed to resolve: HttpContext
Failed to resolve: HttpContext
Failed to resolve: HttpContext
Failed to resolve: HttpContext
Failed to resolve: mk
Failed to resolve: path
Failed to resolve: path
Failed to resolve: empty
Failed to resolve: path
Failed to resolve: HttpRuntime
Failed to resolve: mk
Failed to resolve: HttpContext
Failed to resolve: HttpContext
Failed to resolve: HttpContext
Failed to resolve: HttpContext
Failed to resolve: HttpContext
Failed to resolve: path
Failed to resolve: Http
Failed to resolve: Http.host
Failed to resolve: empty
Failed to resolve: empty
Failed to resolve: mk
Failed to resolve: HttpRuntime
```

Should this fail the build as well? Looks like currently these failures are ignored

### PR DESCRIPTION
**Pull request by theimowski**

### CODE REVIEW

**Comment by ademar** [comment]
Hum .. do we really want to suppress output ? What about if one day FsLibTool outputs a different message ?

**Comment by polytypic** [comment]
[Don't say it is a failure. :)](https://github.com/polytypic/FsiRefGen/commit/12dbcf29eb8964b8fc4e55b7b93a20953c6c8442)

**Comment by ademar** [comment]
@polytypic you could be even more specific `"WARN: Couldn't resolve:"` :)

**Comment by theimowski** [comment]
I think @haf has his own fork of [FsiLibTool here](https://github.com/haf/FsLibTool) and it is the one used by Suave, so the upstream change would have to go there + nuget published and the dependency version updated.

**Comment by polytypic** [comment]
FYI, I'm currently working on making the [`FsiRefGen`](https://github.com/polytypic/FsiRefGen) (formerly `FsLibTool`) usable by others (I originally wrote it just as quick hack for my own projects).  Hopefully I get around to publishing 1.0.0 version during the weekend.

**Comment by theimowski** [comment]
ok cool, then how about just [printing success msg](https://github.com/SuaveIO/suave/pull/468/files) after running the tool?
I know this change might seem irrelevent, but IMO other devs could be less confused

**Pull request merged**
