### PR TITLE
[combinators] adding setHeaderValue function

### PR DESCRIPTION
**Pull request by haf**
Ready to merge if you think this is a good idea.

Justification is in unit test.

Added docs, too.

### CODE REVIEW

**Comment by haf** [comment]
Tests are passing; failing on some CoreCLR thing on AppVeyor

**Comment by ademar** [comment]
Looks good to me - merge it!

**Comment by haf** [comment]
I'm planning to get these four commits published on 1.x too. Alright with you?

**Comment by ademar** [comment]
Sure no problem.

**Pull request merged**
