### PR TITLE
Force "FSharp.Core" "4.1.18" version for netstandard 2.0 + code cleanup

### PR DESCRIPTION
**Pull request by alex-bogomaz**
hello, this should force netcore Suave nugets to depend on "FSharp.Core" ```4.1.18```

### CODE REVIEW

**Comment by haf** [comment]
Is it intentional to remove the System* things?

**Comment by alex-bogomaz** [comment]
Ok - that's probably it.  Please review.
Still do not understand why CI tests are failing - is it possible to trigger CI build once again? 
I've noticed that CI tests are failing from time to time...

**Comment by haf** [comment]
Thanks, rerunning CI now.

**Comment by haf** [comment]
Thank you @alex-bogomaz 

We'll release this update and get Http.fs working on .Net Core shortly.

**Pull request merged**
