### PR TITLE
Performance enhancements (implements buffered output)

### PR DESCRIPTION
**Pull request by ademar**
Minimize the number of `send` operations and buffer churning by buffering output till the buffer is full or `flush` is called.

With these set of changes performance/latency comparable to node.js is achieved.

### CODE REVIEW

**Comment by haf** [comment]
:cake:

**Comment by scitesy** [comment]
I am curious. Is the performance/latency equivalence to node.js with or without a  libuv dependency?

**Comment by ademar** [comment]
@scitesy Hi Scott. This is with the default tcp engine.  At the moment the libuv implementation seems to run slower.

**Comment by scitesy** [comment]
This is an exciting development! This work seems to address some of the questions raised in issue #360?

**Comment by ademar** [comment]
> This work seems to address some of the questions raised in issue #360?

Yes.

**Comment by scitesy** [comment]
Excellent! :) Thank you.

**Pull request merged**
