### PR TITLE
Add `Connection: keep-alive` header when keep-alive is requested

### PR DESCRIPTION
**Pull request by neoeinstein**
Suave does support HTTP 1.1 keep-alive, keeping the socket connection open by default. However, it does not send back a `Connection: Keep-Alive` header in the response for any client. For backward compatibility with HTTP 1.0 clients, such as some benchmarking tools, a keep-alive header is required to keep the connection open. This adds a keep-alive header in the response when the requester has explicitly requested a keep-alive connection and the client is HTTP 1.0.

### CODE REVIEW

**Comment by ademar** [comment]
Nice find. However the fix is incorrect. 

What about if the programmer wants the request to end? With this fix there is no oportunity for him to override the header and close the connection.

I think  you should add the header to the response record somewhere around here https://github.com/SuaveIO/suave/blob/master/src/Suave/Web.fs#L547 before passing the context to the WebPart; then if the programmer wants to end the request he can override it in the WebPart.

Do you follow me? :smiley:

**Comment by neoeinstein** [comment]
I follow you. I'll rework the PR to take that into account.

**Comment by ademar** [comment]
This is good, tests are passing now. Do you mind adding a little test for this ?

**Comment by neoeinstein** [comment]
Certainly. Should be added shortly.

**Comment by ademar** [comment]
This looks great. Thank you very much!

**Pull request merged**
