### PR TITLE
WIP: Update during build

### PR DESCRIPTION
**Pull request by forki**
This is a test and tries to reproduces https://github.com/fsprojects/Paket/issues/1893 on mono

Please do not merge

### CODE REVIEW

**Comment by forki** [comment]
@haf looks like a different error, but still. will need to investigate tomorrow.

**Comment by magicmonty** [comment]
I will try to reproduce this today

**Comment by forki** [comment]
@haf: the update error thta I found is now resolved. But I still can't reproduce https://github.com/fsprojects/Paket/issues/1893

what now?

**Comment by haf** [comment]
Closing as fixed.

**Pull request closed without merging**
