### PR TITLE
[freya] add Freya sample

### PR DESCRIPTION
**Pull request by panesofglass**
@haf @ademar I added a Freya sample to help me debug the issue we've seen running Freya on Suave. I added the sample, but I've not been able to debug successfully. Any help is welcome.

cc: @kolektiv

### CODE REVIEW

**Comment by ademar** [comment]
@panesofglass I'll take a look as soon as possible.

**Comment by panesofglass** [comment]
I cannot quite figure out where the OWIN app is run in order to inspect the environment at that point.

**Comment by panesofglass** [comment]
Ah ha! I found part of the problem! In the last push, I switched to using the lenses directly, and I was able to see that the `responseStreamLens` accessor (Owin.fs, line 608) was indeed hit this time. Something is up inside the Freya.Machine machinery. @kolektiv and I should investigate further on the Freya side, methinks.

**Comment by panesofglass** [comment]
I would still like to add this sample to the examples, but perhaps we should wait until we get Freya.Machine fixed to work with Suave?

**Comment by ademar** [comment]
I've added the example 6db6f596aeddc4b6caaf8829ef84fcb8c13fcd2e in our working branch.

**Comment by panesofglass** [comment]
@ademar Thanks! Should I close this or leave it open for future updates?

**Comment by ademar** [comment]
I've closed it for now.

**Pull request closed without merging**
