### PR TITLE
Authentication.authenticateBasic pass username to protected webpart

### PR DESCRIPTION
**Pull request by xkrt**
Related to https://github.com/SuaveIO/suave/issues/297 and https://github.com/SuaveIO/suave/issues/123

### CODE REVIEW

**Comment by ademar** [comment]
Thanks!

**Comment by xkrt** [comment]
Can you release this please?
I think related issues may be closed.

**Comment by haf** [comment]
@xkrt Great. Now this is a breaking change, so do we want an overload without the protected web part?

**Comment by xkrt** [comment]
@haf well, my opinion is that Suave have version 0.3 and this means that you may not pay too many attention to backward compatabilty. This also means that API will be less swell. So I think we do not want old-style overload:)

**Comment by ademar** [comment]
We are changing the function signature so it will break only their builds which shouldn't be a problem.

**Comment by haf** [comment]
Hmm... OK.

**Pull request merged**
