### PR TITLE
upgrade to .NET Core rc2 with example

### PR DESCRIPTION
**Pull request by enricosada**
Use released [.NET Core SDK rc2](https://www.microsoft.com/net) and fix `examples/Example` to run with .NET Core 

- use released .net core rc2
  - fix dependencies version (use .net core rc2)
  - use latest FSharp.Core package (netstandard1.5 instead of dnxcore50)
- use released .net core sdk rc2 ( the .net cli )
  - updated project.json sintax to rc2
  - use `dotnet-mergenupkg` version 0.10.* compatible with rc2
- fix rake to install .net core only if the .net core sdk rc2 version not is installed
- fix `examples/Example` to run with .net core

**NOTE** i updated version to `-alpha2` instead of `-alpha`, because it need to resolve new package. dunno if this is the right way for suave repo.

### CODE REVIEW

**Comment by haf** [comment]
Cool

**Comment by enricosada** [comment]
i am testing osx now ( @haf  i know osx is required :smile: )

btw performance  (using `examples/Example` like `ab -t 50 -n 1000 -A foo:bar 127.0.0.1:8082/hello` ) is pretty much the same as .net full, so nice i think. on windows. i'll wait for osx benchmark when ready

**Comment by ademar** [comment]
Beautiful :)

On Fri, May 20, 2016 at 11:24 AM, Enrico Sada <notifications@github.com>
wrote:

> i am testing osx now ( @haf <https://github.com/haf> i know osx is
> required 😄 )
>
> btw performance (using examples/Example like ab -t 50 -n 1000 -A foo:bar
> 127.0.0.1:8082/hello ) is pretty much the same as .net full, so nice i
> think. on windows. i'll wait for osx benchmark when ready
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SuaveIO/suave/pull/439#issuecomment-220636431>
>



-- 
Ademar Gonzalez
+1-647-891-3606
http://ademar.name
https://github.com/ademar

**Comment by enricosada** [comment]
osx i am reinstalling el capitan, so i'll test tomorrow i think

**in docker works**, host from my windows 10 ( i really love docker client beta btw :heart:  )

- run docker image of .NET Core ( https://www.microsoft.com/net/core#docker )
- cloned this pr branch inside container ( i am lazy )
- cd `examples/Example`
- set a [personal feed](https://www.myget.org/F/enrico-ci/api/v3/index.json) in Nuget.config with the built suave package
- dotnet restore
- dotnet run

docker_suave_netcore

**Comment by enricosada** [comment]
And osx works too, without changes.
i need to test the whole rakefile, but locally build and run example works!

screen shot 2016-05-21 at 15 13 31


So far:

- win
- osx
- docker

I'll fix the appveyor failure asap, so i hope you can publish an alpha package on nuget 😄

**Comment by haf** [comment]
```
log  : Restore failed in 58166ms.
info :   NotFound https://myget-2e16.kxcdn.com/artifacts/fsharp-daily/nuget/v3/flatcontainer/dotnet-mergenupkg/index.json 319ms
info :   OK https://api.nuget.org/v3-flatcontainer/dotnet-mergenupkg/index.json 567ms
info :   GET https://api.nuget.org/v3-flatcontainer/dotnet-mergenupkg/0.10.2/dotnet-mergenupkg.0.10.2.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/dotnet-mergenupkg/0.10.2/dotnet-mergenupkg.0.10.2.nupkg 812ms
```

**Comment by gregwebs** [comment]
@enricosada thank you!

**Comment by enricosada** [comment]
ok @haf can you pls try now?

i used a clean osx 10.11 + mono, dotnet sdk rc2 not in path  so is downloaded by rakefile. 
You can also install dotnet sdk rc2 from http://dot.net so it's already installed and the rakefile doesnt download it (it's in PATH)

What i have done:

to create the package

```
bundle exec rake nugets
bundle exec rake dotnetcli:do_netcorepackage
bundle exec rake dotnetcli:merge
```

after that `build/pkg` contains the new package merged, so i can used that.
the examples/Example/Nuget.config has a feed the built package directory

```
cd examples/Example
dotnet restore # or ../../tools/coreclr/dotnet restore if dotnet is not in path or installed globally
dotnet run # or ../../tools/coreclr/dotnet restore if dotnet is not in path or installed globally
```

**Comment by enricosada** [comment]
Ok, fixed also https://github.com/SuaveIO/Suave-CoreCLR-sample .

works xplat ( ubuntu 14.04, osx 10.11, win, docker) with the same instructions.
pls remove the temporary feed in Nuget.config after the new package is published

**Comment by ctaggart** [comment]
I tried reproducing this, but I get an error with `bundle exec rake nugets`:
```
FSC:  warning FS2003: An AssemblyInformationalVersionAttribute specified version '2.0.0-alpha2.093dc9', but this value is invalid and has been ignored
Configuration: Release Platform: AnyCPU
rake aborted!
ArgumentError: invalid byte sequence in US-ASCII
/var/lib/gems/2.1.0/gems/albacore-2.5.6/lib/albacore/tools.rb:14:in `split'
/var/lib/gems/2.1.0/gems/albacore-2.5.6/lib/albacore/tools.rb:14:in `git_release_notes'
/var/lib/gems/2.1.0/gems/albacore-2.5.6/lib/albacore/nuget_model.rb:361:in `from_xxproj'
/home/vscode/suave/tools/paket_pack.rb:10:in `create_nuspec'
```
Full output of `bundle exec rake nugets --trace > suave-build-invalid-byte-sequence.txt 2>&1`
https://gist.github.com/ctaggart/8f0134e5412916d5e49e74d1e8844095

**Comment by haf** [comment]
@ctaggart I think I fixed the error with ruby https://github.com/Albacore/albacore/commit/4cf029742a20d44796d41cb3940f3e8e2d33fbb5 – I've updated Suave to use this fix. Also, I think that it's the `dotnetcli:merge` that builds the nugets for CoreCLR, not the `nugets` task.

**Comment by enricosada** [comment]
- `nugets` => build normal suave package in `build/pkg`
- `dotnetcli:do_netcorepackage` => build `src/Suave/project.json` and create a nuget package for netstandard in `src/Suave/bin/Release/Suave.2.0.0.nupkg`
- `dotnetcli:merge` => copy assemblies and metadata from `src/Suave/bin/Release/Suave.2.0.0.nupkg` into `build/pkg/Suave.2.0.0.nupkg`

**Comment by haf** [comment]
@enricosada Sweet. Appreciate the reformat...

Now doing package works, but not the merge:

```
.NET Core SDK 1.0.0-preview1-002702 not found. Downloading and installing in ./tools/coreclr
tar xf tools/dotnet-dev-osx-x64.1.0.0-preview1-002702.tar.gz --directory tools/coreclr
semver: looking at /Users/h/dev/suave/suave/src/.semver
semver: looking at /Users/h/dev/suave/suave/.semver
/Users/h/dev/suave/suave/tools/coreclr/dotnet mergenupkg --source "../../build/pkg/Suave.2.0.0-alpha2.nupkg" --other "bin/Release/Suave.2.0.0-alpha2-dotnetcli.nupkg" --framework netstandard1.5
nupkg '../../build/pkg/Suave.2.0.0-alpha2.nupkg' not found
rake aborted!
```

The folder `build` is empty.

**Comment by enricosada** [comment]
Have you run `rake nugets` before?

**Comment by ctaggart** [comment]
The Suave-CoreCLR-Sample works great! Here is a movie demo of that and more:
https://youtu.be/qjH1yaWcUHI

**Comment by haf** [comment]
@enricosada No I didn't, runing that before worked. Is this the intended tree afterwards?

```
├── lib
│   └── net40
│       ├── Suave.2.0.0-alpha2-dotnetcli.nupkg
│       ├── Suave.2.0.0-alpha2-dotnetcli.symbols.nupkg
│       ├── Suave.dll
│       ├── Suave.dll.config
│       ├── Suave.dll.mdb
│       └── Suave.xml
└── package
    └── services
        └── metadata
            └── core-properties
                └── coreProp.psmdcp

7 directories, 17 files
```

**Comment by haf** [comment]
@enricosada I've pushed v2.0.0-alpha3 – can you verify it works with the sample project we worked on?

**Comment by gregwebs** [comment]
I can confirm that 2.0.0-alpha3 compiles and runs with the dotnet preview whereas 1.1.2 did not. I am just importing the module, not testing out an app.

**Comment by enricosada** [comment]
No, Alpha3 doesnt work. Doesnt have netstandard1.5
From source now is ok

**Pull request merged**
