### PR TITLE
Refactor towards BAD REQUEST on parsing errors

### PR DESCRIPTION
**Pull request by haf**
Related to #228

### CODE REVIEW

**Comment by haf** [comment]
We need to capture the error case as well;

```
[V] 2015-05-18T15:35:29.0210400Z: stopping tcp server, reason: 'tcpIpServer async cancelled' [Tcp.stop_tcp]
[V] 2015-05-18T15:35:29.0212120Z: stopped tcp server [Tcp.stop_tcp]
```

 To be done. But it's better than hanging forever.

**Comment by ademar** [comment]
I like these changes :+1

**Comment by ademar** [comment]
Although I think I would prefer a function name there rather than the operator.

**Comment by haf** [comment]
@ademar I'm not sure 4bc7f3f is the right solution; because it's still not returning BAD_REQUEST properly but causing a server shut down... Insights? I'm writing a unit test that exposes this new behaviour, and then we can go around throughout the server and remove all calls to `failwith` and `failwithf`.

I'm also thinking this code could use a good fuzzer to ensure we never block/crash.

**Comment by ademar** [comment]
Cool, I'll check out the branch and investigate.

**Comment by haf** [comment]
@ademar I pushed a failing test

**Comment by haf** [comment]
It's failing here:

```
        let! fieldName =
          (headerParams.TryLookup "name" |> Choice.map (String.trimc '"'))
          @|! "Key 'name' was not present in 'content-disposition'"
```

Because the post looks like:

```
// 8<
--/tkQKiFqMgZt:mHzua_JFrUFWHgNid
Content-Type: multipart/mixed; boundary=-idczlATz:FmvuIs'aHQSrGltky:Td
Content-Disposition: form-data; name="files"

---idczlATz:FmvuIs'aHQSrGltky:Td
Content-Disposition: file; filename="file1.txt"
Content-Type: text/plain
// >8
```

I'm posting two files under the same form field.

**Comment by haf** [comment]
#251 - continuation of this

**Pull request closed without merging**
