### PR TITLE
Fix for #547 (Signalr)

### PR DESCRIPTION
**Pull request by ademar**
fix for #547

### CODE REVIEW

**Comment by TheAngryByrd** [comment]
Since we have to supply `"/signalr"` here:
```
let owin = builder.Build() |> OwinApp.ofAppFunc "/signalr"
```

does that mean we can't chain things together on the same builder?  Like `builder.UseCookieAuthentication().MapSignalR().UseNancy()` ?

**Comment by ademar** [comment]
It depends, in this case SignalR is using `requestPathBase` to derive the connect URL. See the following links:

https://github.com/aspnet/SignalR-Server/blob/9680e9c2c185a19604390003a6f10489d0538a56/src/Microsoft.AspNetCore.SignalR.Server/Hosting/RequestExtensions.cs#L10

https://github.com/aspnet/SignalR-Server/blob/9680e9c2c185a19604390003a6f10489d0538a56/src/Microsoft.AspNetCore.SignalR.Server/Transports/TransportDisconnectBase.cs#L218

So I guess in this case there is no way around it.

**Comment by haf** [comment]
```
[17:44:53 ERR] e2e/Setting a path in Suave should mount an OWIN app at that path and set requestPathBase failed in 00:00:00.0137786. 

Http Status Code. Actual value was OK but had expected it to be NotFound.
```

**Comment by ademar** [comment]
yeah i saw that .. I'm trying to go to the end of it; so far it seems like SignalR does not like something like:

```
owin.RequestPathBase = "/signalr" and 

owin.RequestPath = "/js"  
```

which is correct according to spec

**Comment by ademar** [comment]
relevant: http://stackoverflow.com/questions/25648722/how-are-owincontext-request-path-and-pathbase-populated

**Comment by ademar** [comment]
OK, this should do it.

I found that the SignalR middleware was (trying to) alter the properties `RequestPathBase` and `RequestPath` which our previous implementation with the `constant` lense was not allowing. I introduced a new `writeable` lense to make those properties read/write.

@TheAngryByrd note that now we are calling the middleware with an empty string.

```fsharp
let owin = builder.Build() |> OwinApp.ofAppFunc ""
```

**Comment by TheAngryByrd** [comment]
🎸

**Pull request merged**
