### PR TITLE
[WIP] use .NET Core sdk preview2 and .NET Core 1.0 rtm

### PR DESCRIPTION
**Pull request by enricosada**
- [x] update install rake script
- [x] update Suave project.json
- [ ] update examples

using suave as test case for the fixed sdk preview2

### CODE REVIEW

**Comment by haf** [comment]
Funny that they just pull the package...

**Comment by enricosada** [comment]
@haf @ademar if you see issues with appveyor, check if dotnet version is preview2 (now it's installed by default)
meanwhile use preview1 in appveyor, see https://github.com/fsharp/FSharp.Compiler.Service/pull/598

**Comment by haf** [comment]
@enricosada Thank you very much! :)

**Comment by enricosada** [comment]
np, tomorrow i'll send another pr to remove the nuget.config, because the vf# team is pushing the 2 remaining package on nuget.org!! easier for everyone

**Pull request merged**
